import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { SceneDocumentSchema } from "../src/schema/scene";

describe("cross-language schema roundtrip", () => {
  it("parses Scene JSON generated by Python models", () => {
    const snapshotPath = resolve(
      process.cwd(),
      "..",
      "python",
      "tests",
      "snapshots",
      "basic_scene.json"
    );

    const payload = JSON.parse(readFileSync(snapshotPath, "utf-8"));
    const parsed = SceneDocumentSchema.parse(payload);

    expect(parsed.nodes.length).toBe(2);
    expect(parsed.edges.length).toBe(1);
    expect(parsed.render_settings.width).toBe(1280);
  });
});
